name: SDmedia
favicon: null
layout_spectrum: 0.5319612976163626
typography_spectrum: 0.578417114680633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5241074778605253
  lightness: 0.9241439665202051
  saturation: 0.8339304877445102
  rhythmicContrast: 0.5388539277482778
purpose: []
